[build-system]
requires = ["setuptools>=42",
            "setuptools_scm[toml]>=6.2"]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
write_to = "src/fass/version.py"

[tool.pytest.ini_options]
minversion = "6.0"
testpaths = [
    "src/fass/tests"
]
